In [ ]:
import tensorflow as tf
print ("tensorflow:",tf.__version__)

In [ ]:
mnist = tf.keras.datasets.mnist
(x_train,x_test),(y_train,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0 ,x_test/255.0

In [ ]:
model = tf.keras.models.Sequential ([
        tf.keras.layers.Flatten(input_shape = (28,28)),
        tf.keras.layers.Dense(128, activation = "relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
        ])


In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.65022874,  0.03647728,  0.05297394,  0.12734461,  0.47727743,
        -0.11158115, -0.36390197,  0.631811  ,  0.12909822,  0.2598136 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.1513423 , 0.08192406, 0.08328675, 0.08971699, 0.1273059 ,
        0.07064973, 0.05489452, 0.14858043, 0.08987445, 0.10242482]],
      dtype=float32)>

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()



model.complile(
    optimizer = 'adam',
loss = loss_fn,
metrics = ['accuracy']
               )

ValueError: `labels.shape` must equal `logits.shape` except for the last dimension. Received: labels.shape=(784,) and logits.shape=(1, 10)

In [ ]:
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_train,y_test,verbase=2)