In [1]:
import tensorflow as tf
print ("tensorflow:",tf.__version__)

tensorflow: 2.15.0


In [2]:
mnist = tf.keras.datasets.mnist
(x_train,x_test),(y_train,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0 ,x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential ([
        tf.keras.layers.Flatten(input_shape = (28,28)),
        tf.keras.layers.Dense(128, activation = "relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
        ])


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5756172 , -0.2771594 ,  0.01222466,  0.26058662,  0.28426653,
         0.06321755,  0.14686036, -0.30785432, -0.10206494, -0.32201594]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.16524637, 0.07043293, 0.09407054, 0.12059127, 0.12348095,
        0.09899188, 0.10762799, 0.06830384, 0.08391088, 0.06734337]],
      dtype=float32)>

In [ ]:
labels = labels[:10]

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()



model.complile(
    optimizer = 'adam',
loss = loss_fn,
metrics = ['accuracy']
               )

ValueError: `labels.shape` must equal `logits.shape` except for the last dimension. Received: labels.shape=(784,) and logits.shape=(1, 10)

In [ ]:
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_train,y_test,verbase=2)