In [2]:
import tensorflow as tf
print ("tensorflow:",tf.__version__)


tensorflow: 2.15.0


In [3]:
mnist = tf.keras.datasets.mnist
(x_train,x_test),(y_train,y_test) = mnist.load_data()
x_train, x_test = x_train/255.0 ,x_test/255.0

In [4]:
model = tf.keras.models.Sequential ([
        tf.keras.layers.Flatten(input_shape = (28,28)),
        tf.keras.layers.Dense(128, activation = "relu"),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(10)
        ])


In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.7767826 ,  0.3696542 , -0.8752696 ,  0.02781369, -0.10827994,
         0.3480868 , -0.2905947 , -0.69402623, -0.21161054, -0.24109565]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions)

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.05405159, 0.17009817, 0.04898195, 0.1208482 , 0.10547158,
        0.16646887, 0.08789359, 0.05871501, 0.0951173 , 0.0923537 ]],
      dtype=float32)>

In [8]:
y_train.shape

(10000, 28, 28)

In [9]:
predictions.shape

(1, 10)

In [10]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()



model.compile(
    optimizer = 'adam',
loss = loss_fn,
metrics = ['accuracy']
)

ValueError: `labels.shape` must equal `logits.shape` except for the last dimension. Received: labels.shape=(784,) and logits.shape=(1, 10)

In [ ]:
model.fit(x_train, y_train, epochs=5)
model.evaluate(x_train,y_test,verbase=2)